export const instructionalLevelMap = {
    AP: 'Advanced Placement',
    BAS: 'Basic',
    EL: 'English Learner',
    DE: 'Dual Enrollment',
    GEN: 'General',
    GTAA: 'Gifted and Talented/Advanced Academic',
    HON: 'Honors Level',
    HSE: 'High School Equivalent',
    IB: 'International Baccalaureate',
    REM: 'Remedial',
    SWD: 'Students with Disabilities',
    UT: 'Untracked'
};

export const scedMapping = {
    1: 'English Language and Literature',
    2: 'Mathematics',
    3: 'Life and Physical Sciences',
    4: 'Social Sciences and History',
    5: 'Visual and Performing Arts',
    6: 'Foreign Language and Literature',
    7: 'Religious Education and Theology',
    8: 'Physical, Health, and Safety Education',
    9: 'Military Science',
    10: 'Information Technology',
    11: 'Communication and Audio\\/Visual Technology',
    12: 'Business and Marketing',
    13: 'Manufacturing',
    14: 'Health Care Sciences',
    15: 'Public, Protective, and Government Services',
    16: 'Hospitality and Tourism',
    17: 'Architecture and Construction',
    18: 'Agriculture, Food, and Natural Resources',
    19: 'Human Services',
    20: 'Transportation, Distribution and Logistics',
    21: 'Engineering and Technology',
    22: 'Miscellaneous',
    23: 'Non-Subject-Specific',
    24: 'World Languages'
};

export const csscMapping = {
    1: '01 AGRIBUSINESS AND AGRICULTURAL PRODUCTION',
    2: '02 AGRICULTURAL SCIENCES',
    3: '03 RENEWABLE NATURAL RESOURCES',
    4: '04 ARCHITECTURE AND ENVIRONMENTAL DESIGN',
    5: '05 AREA AND ETHNIC STUDIES',
    6: '06 BUSINESS AND MANAGEMENT',
    7: '07 BUSINESS AND OFFICE',
    8: '08 MARKETING AND DISTRIBUTION',
    9: '09 COMMUNICATIONS',
    10: '10 COMMUNICATION TECHNOLOGIES',
    11: '11 COMPUTER AND INFORMATION SCIENCES',
    12: '12 CONSUMER, PERSONAL, AND MISCELLANEOUS SERVICES',
    13: '13 EDUCATION',
    14: '14 ENGINEERING',
    15: '15 ENGINEERING AND ENGINEERING-RELATED TECHNOLOGIES',
    16: '16 FOREIGN LANGUAGES',
    17: '17 ALLIED HEALTH',
    18: '18 HEALTH SCIENCES',
    19: '19 HOME ECONOMICS.',
    20: '20 VOCATIONAL HOME ECONOMICS',
    21: '21 INDUSTRIAL ARTS',
    22: '22 LAW',
    23: '23 LETTERS/ENGLISH',
    24: '24 LIBERAL/GENERAL STUDIES',
    25: '25 LIBRARY AND ARCHIVAL SCIENCES',
    26: '26 LIFE SCIENCES',
    27: '27 MATHEMATICS',
    28: '28 MILITARY SCIENCES',
    29: '29 MILITARY TECHNOLOGIES',
    30: '30 MULTI/INTERDISCIPLINARY STUDIES',
    31: '31 PARKS AND RECREATION',
    32: '32 BASIC SKILLS',
    33: '33 CITIZENSHIP/CIVIC ACTIVITIES',
    34: '34 HEALTH RELATED ACTIVITIES',
    35: '35 INTERPERSONAL SKILLS',
    36: '36 LEISURE AND RECREATIONAL ACTIVITIES',
    37: '37 PERSONAL AWARENESS',
    38: '38 PHILOSOPY AND RELIGION',
    39: '39 THEOLOGY',
    40: '40 PHYSICAL SCIENCES',
    41: '41 SCIENCE TECHNOLOGIES',
    42: '42 PSYCHOLOGY',
    43: '43 PROTECTIVE SERVICES',
    44: '44 PUBLIC AFFAIRS',
    45: '45 SOCIAL SCIENCES',
    46: '46 CONSTRUCTION TRADES',
    47: '47 MECHANICS AND REPAIRERS',
    48: '48 PRECISION PRODUCTION',
    49: '49 TRANSPORTATION AND MATERIAL MOVING',
    50: '50 VISUAL AND PERMORMING ARTS',
    51: '51 EXECUTIVE INTERNSHIP',
    52: '52 GENERAL (INCLUDING PRE-VOCATIONAL PROGRAMS) EMH',
    54: '54 SPECIAL EDUCATION',
    55: '55 SPECIAL EDUCATION - VOCATIONAL, CAREER PREPARATION, CAREER EXPLORATION',
    56: '56 SPECIAL EDUCATION - RESOURCE CURRICULUM',
};
