AWSTemplateFormatVersion: '2010-09-09'
Description: Naviance academic-planner export lambda
Transform: AWS::Serverless-2016-10-31
Resources:
  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://data-channels-processor-deployments-dev/e9bbc2001fb0dfb8e445f8eb8c932d8d
      FunctionName: cf-naviance-dc-ap-import
      Handler: dist/index.lambdaHandler
      Timeout: 900
      MemorySize: 2048
      Runtime: nodejs12.x
      Policies:
      - Statement:
          Action: lambda:InvokeFunction
          Effect: Allow
          Resource: arn:aws:lambda:*:*:function:cdk-data-channels-core-st-cfdatachannelsloggrabber
      - Statement:
        - Sid: SSMGetParameterPolicy
          Effect: Allow
          Action:
          - ssm:GetParameter
          Resource: arn:aws:ssm:*:*:parameter/academic-planner-dev/*
      - Statement:
        - Sid: SSMGetParameterPolicy
          Effect: Allow
          Action:
          - ssm:GetParameter
          Resource: arn:aws:ssm:*:*:parameter/academic-planner-qa/*
