AWSTemplateFormatVersion: '2010-09-09'
Description: Naviance academic-planner export lambda
Transform: AWS::Serverless-2016-10-31
Resources:
  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://data-channels-processor-deployments-dev/0ef08f99698571e243bbd5995ef8b1c1
      FunctionName: cf-naviance-dc-ap-import-dev
      Handler: dist/index.lambdaHandler
      Timeout: 900
      MemorySize: 2048
      Runtime: nodejs10.x
      Policies:
      - Statement:
        - Sid: SSMGetParameterPolicy
          Effect: Allow
          Action:
          - ssm:GetParameter
          Resource: arn:aws:ssm:*:*:parameter/academic-planner-dev/*
      - Statement:
        - Sid: SSMGetParameterPolicy
          Effect: Allow
          Action:
          - ssm:GetParameter
          Resource: arn:aws:ssm:*:*:parameter/academic-planner-qa/*
