AWSTemplateFormatVersion: '2010-09-09'
Description: Data-Channels Builtins Lambda
Transform: AWS::Serverless-2016-10-31
Resources:
  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://data-channels-processor-deployments-dev/7674a5009c718d7d72e03a42eeb75760
      FunctionName: data-channels-BuiltInProcessor
      Handler: dist/index.BuiltInHandler
      Policies:
        - Statement:
            Action: lambda:InvokeFunction
            Effect: Allow
            Resource: arn:aws:lambda:us-east-1:578210663060:function:cdk-data-channels-core-st-cfdatachannelsloggrabber-*
        - Statement:
            - Action:
                - ssm:GetParameter
              Effect: Allow
              Resource: arn:aws:ssm:*:*:parameter/data-channels/hello-*
              Sid: SSMGetParameterPolicy
      Runtime: nodejs10.x
      Timeout: 300
