AWSTemplateFormatVersion: '2010-09-09'
Description: Data-Channels Builtins Lambda
Transform: AWS::Serverless-2016-10-31
Resources:
  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://data-channels-processor-deployments-dev/4b2d691ec0f6f5e45fe64286a22a0c28
      FunctionName: data-channels-BuiltInProcessor
      Handler: dist/index.builtInHandler
      Timeout: 300
      MemorySize: 3008
      Runtime: nodejs12.x
      Policies:
      - Statement:
          Action: lambda:InvokeFunction
          Effect: Allow
          Resource: arn:aws:lambda:*:*:function:cdk-data-channels-core-st-cfdatachannelsloggrabber
      - Statement:
        - Sid: SSMGetParameterPolicy
          Effect: Allow
          Action:
          - ssm:GetParameter
          Resource: arn:aws:ssm:*:*:parameter/data-channels/hello-*
      - Statement:
        - Sid: SNSPublishPolicy
          Effect: Allow
          Action:
          - SNS:Publish
          Resource: '*'
      - Statement:
        - Sid: SESSendPolicy
          Effect: Allow
          Action:
          - SES:SendEmail
          - SES:SendRawEmail
          Resource: '*'
      - Statement:
        - Sid: S3WorkspaceListPolicy
          Action:
          - s3:GetBucketLocation
          - s3:ListBucket
          - s3:ListBucketMultipartUploads
          - s3:ListMultipartUploadParts
          Effect: Allow
          Resource: arn:aws:s3:::data-channels-work-dev
      - Statement:
        - Sid: S3WorkspaceObjectPolicy
          Action:
          - s3:*
          Effect: Allow
          Resource: arn:aws:s3:::data-channels-work-dev/workspace/athena/*
      - Statement:
        - Sid: AthenaQueryPolicy
          Action:
          - athena:StartQueryExecution
          - athena:GetQueryExecution
          Effect: Allow
          Resource: arn:aws:athena:*:*:workgroup/primary
      - Statement:
        - Sid: GlueDBPolicy
          Action:
          - glue:*
          Effect: Allow
          Resource:
          - arn:aws:glue:*:*:catalog
          - arn:aws:glue:*:*:database/dchan*
          - arn:aws:glue:*:*:table/dchan*
          - arn:aws:glue:*:*:userDefinedFunction/dchan*
