AWSTemplateFormatVersion: '2010-09-09'
Description: Data-Channels Builtins Lambda
Transform: AWS::Serverless-2016-10-31
Resources:
  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ss-data-channels-processor-deployments-platsandbox/e10e2bbb07585bf0dc14cae98acd1a80
      FunctionName: ss-data-channels-BuiltInProcessor
      Handler: dist/index.builtInHandler
      Timeout: 300
      MemorySize: 3008
      Runtime: nodejs12.x
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      PermissionsBoundary: arn:aws:iam::701991169879:policy/tf-iam-permission-boundary
      Policies:
      - Statement:
        - Sid: SSMGetParameterPolicy
          Effect: Allow
          Action:
          - ssm:GetParameter
          Resource:
          - arn:aws:ssm:*:*:parameter/data-channels/hello-*
          - arn:aws:ssm:*:*:parameter/data-channels-builtin/*
      - Statement:
        - Sid: SNSPublishPolicy
          Effect: Allow
          Action:
          - SNS:Publish
          Resource: '*'
      - Statement:
        - Sid: SESSendPolicy
          Effect: Allow
          Action:
          - SES:SendEmail
          - SES:SendRawEmail
          Resource: '*'
      - Statement:
        - Sid: S3WorkspaceListPolicy
          Action:
          - s3:GetBucketLocation
          - s3:ListBucket
          - s3:ListBucketMultipartUploads
          - s3:ListMultipartUploadParts
          Effect: Allow
          Resource: arn:aws:s3:::data-channels-work-*
      - Statement:
        - Sid: S3WorkspaceObjectPolicy
          Action:
          - s3:*
          Effect: Allow
          Resource: arn:aws:s3:::*data-channels-work-*/workspace/*
      - Statement:
        - Sid: AthenaQueryPolicy
          Action:
          - athena:StartQueryExecution
          - athena:GetQueryExecution
          Effect: Allow
          Resource: arn:aws:athena:*:*:workgroup/primary
      - Statement:
        - Sid: GlueDBPolicy
          Action:
          - glue:*
          Effect: Allow
          Resource:
          - arn:aws:glue:*:*:catalog
          - arn:aws:glue:*:*:database/dchan*
          - arn:aws:glue:*:*:database/data-channel*
          - arn:aws:glue:*:*:table/dchan*
          - arn:aws:glue:*:*:table/data-channel*
          - arn:aws:glue:*:*:job/data-channel*
          - arn:aws:glue:*:*:userDefinedFunction/dchan*
      - Statement:
        - Sid: GluePassRole
          Action:
          - iam:PassRole
          Effect: Allow
          Resource:
          - arn:aws:iam::*:role/*data-channel*
      - Statement:
        - Sid: S3ClamAVPolicy
          Action:
          - s3:*
          Effect: Allow
          Resource: arn:aws:s3:::*data-channels-work-*/clamav/*
