AWSTemplateFormatVersion: '2010-09-09'
Description: Data-Channels Builtins Lambda
Transform: AWS::Serverless-2016-10-31
Resources:
  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://data-channels-processor-deployments-dev/5c65bb3eba5c330d4bc2f9dba45d98f8
      FunctionName: data-channels-BuiltInProcessor
      Handler: dist/index.BuiltInHandler
      Timeout: 300
      Runtime: nodejs10.x
      Policies:
      - Statement:
          Action: lambda:InvokeFunction
          Effect: Allow
          Resource: arn:aws:lambda:*:*:function:cdk-data-channels-core-st-cfdatachannelsloggrabber
      - Statement:
        - Sid: SSMGetParameterPolicy
          Effect: Allow
          Action:
          - ssm:GetParameter
          Resource: arn:aws:ssm:*:*:parameter/data-channels/hello-*
