AWSTemplateFormatVersion: '2010-09-09'
Description: Data-Channels Builtins Lambda
Transform: AWS::Serverless-2016-10-31
Resources:
  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://data-channels-processor-deployments-dev/8f56d658f310347b7c1af6e6a96293f2
      FunctionName: data-channels-BuiltInProcessor
      Handler: dist/index.BuiltInHandler
      Timeout: 300
      MemorySize: 3008
      Runtime: nodejs12.x
      Policies:
      - Statement:
          Action: lambda:InvokeFunction
          Effect: Allow
          Resource: arn:aws:lambda:*:*:function:cdk-data-channels-core-st-cfdatachannelsloggrabber
      - Statement:
        - Sid: SSMGetParameterPolicy
          Effect: Allow
          Action:
          - ssm:GetParameter
          Resource: arn:aws:ssm:*:*:parameter/data-channels/hello-*
      - Statement:
        - Sid: SNSPublishPolicy
          Effect: Allow
          Action:
          - SNS:Publish
          Resource: '*'
      - Statement:
        - Sid: SESSendPolicy
          Effect: Allow
          Action:
          - SES:SendEmail
          - SES:SendRawEmail
          Resource: '*'
