AWSTemplateFormatVersion: '2010-09-09'
Description: Data-Channels Builtins Lambda
Resources:
  ProcessorFunction:
    Properties:
      CodeUri: s3://data-channels-processor-deployments-sandbox/343f11fab7be90cadc0250714f7f420f
      FunctionName: data-channels-BuiltInProcessor
      Handler: dist/index.BuiltInHandler
      Policies:
        - Statement:
            Action: lambda:InvokeFunction
            Effect: Allow
            Resource: arn:aws:lambda:*:*:function:cdk-data-channels-core-st-cfdatachannelsloggrabber
        - Statement:
            - Action:
                - ssm:GetParameter
              Effect: Allow
              Resource: arn:aws:ssm:*:*:parameter/data-channels/hello-*
              Sid: SSMGetParameterPolicy
        - Statement:
          -
            Action:
              - s3:ListBucket
            Effect: Allow
            Resource:
              arn:aws:s3:::data-channels-work-dev
          -
            Action:
              - s3:*
            Effect: Allow
            Resource:
              arn:aws:s3:::data-channels-work-dev/workspace/athena/*
          -
            Action:
              - athena:StartQueryExecution
              - athena:GetQueryExecution
            Effect: Allow
            Resource:
              arn:aws:athena:*:*:workgroup/primary
      Runtime: nodejs12.x
      Timeout: 300
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
