AWSTemplateFormatVersion: '2010-09-09'
Description: Data-Channels Builtins Lambda
Transform: AWS::Serverless-2016-10-31

Resources:
  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: "./"
      FunctionName: data-channels-BuiltInProcessor
      Handler: dist/index.BuiltInHandler
      Timeout: 300
      Runtime: nodejs10.x
      Policies:
        - Statement:
            - Action: [ 'lambda:InvokeFunction' ]
              Effect: Allow
              Resource: 'arn:aws:lambda:us-east-1:578210663060:function:cdk-data-channels-core-st-cfdatachannelsloggrabber-2FGI0R0FZRSI'

        - Statement:
          - Sid: SSMGetParameterPolicy
            Effect: Allow
            Action:
            - ssm:GetParameter
            Resource: 'arn:aws:ssm:*:*:parameter/data-channels/hello-*'
