AWSTemplateFormatVersion: '2010-09-09'
Description: Naviance academic-planner export lambda
Transform: AWS::Serverless-2016-10-31
Resources:
  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://data-channels-processor-deployments-navprod/f98982a9a90efe6f8ab68a5be989c9ff
      FunctionName: cf-naviance-dc-ap-export-navprod
      Handler: dist/index.exportHandler
      Timeout: 900
      MemorySize: 3000
      Runtime: nodejs10.x
      Policies:
      - Statement:
        - Sid: SSMGetParameterPolicy
          Effect: Allow
          Action:
          - ssm:GetParameter
          Resource: arn:aws:ssm:*:*:parameter/academic-planner-prod/*
